global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - tsmp_rules.yml

scrape_configs:
  - job_name: 'tsmp-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['127.0.0.1:8000']

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['127.0.0.1:9093']
