name: pytest (sqlite)
on:
  push: { branches: ["**"] }
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install fastapi uvicorn sqlalchemy pandas pyarrow pydantic mlflow pytest
      - name: Run tests (sqlite fallback)
        env:
          POSTGRES_DSN: sqlite:///ci.db
          MLFLOW_TRACKING_URI: file:./mlruns
        run: pytest -q
