# .github/workflows/pytest.yml
name: pytest (sqlite)
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pyarrow  # parquet 読み出し用
      - name: Run tests
        env:
          POSTGRES_DSN: ""   # CI は sqlite フォールバック
          MLFLOW_TRACKING_URI: "file:./mlruns"
        run: pytest -q
